# SonarQube project settings
sonar.coverage.exclusions=\
  **/*.test.ts,\
  **/*.test.tsx,\
  **/*.spec.ts,\
  **/*.spec.tsx,\
  **/setupTests.ts,\
  src/main.tsx,\
  src/App.tsx
sonar.cpd.exclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
